### ISSUE TITLE
Section 1: Contradictory text?

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#10]
Section 1:  The first and last sentences of this
paragraph seem to contradict each other.  Also, we do not see
the word "rejection" in Appendix A.  Will this text be clear to
readers?

Original:
 This document does not cover rejection sampling methods, sometimes
 referred to as "try-and-increment" or "hunt-and-peck," because the
 goal is to describe algorithms that can plausibly be computed in
 constant time.  Use of these rejection methods is NOT RECOMMENDED,
 because they have been a perennial cause of side-channel
 vulnerabilities.  See Dragonblood [VR20] as one example of this
 problem in practice, and see Appendix A for a further description of
 rejection sampling methods.

**Comment by chris-wood** [comment]
I agree it's a bit confusing. How about the following (changes in **bold**)?

OLD:
This document does not cover rejection sampling methods, sometimes
referred to as "try-and-increment" or "hunt-and-peck," because the
goal is to describe algorithms that can plausibly be computed in
constant time. Use of these rejection methods is NOT RECOMMENDED,
because they have been a perennial cause of side-channel
vulnerabilities. See Dragonblood [VR20] as one example of this
problem in practice, and see Appendix A for a further description of
rejection sampling methods.

NEW:
This document does not **specify probabilistic** rejection sampling methods, sometimes
referred to as "try-and-increment" or "hunt-and-peck," because the
goal is to **specify** algorithms that can plausibly be computed in
constant time. Use of these **probabilistic** rejection methods is NOT
RECOMMENDED, because they have been a perennial cause of side-channel
vulnerabilities. See Dragonblood [VR20] as one example of this
problem in practice, and see Appendix A for **an informal description of rejection
sampling methods and the timing side-channels they introduce.**

**Comment by sginoza** [comment]
closed by #15
