### ISSUE TITLE
Terminology 

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#46]
The following terms appear to be used inconsistently in this
document.  Please let us know which form is preferred.

 abort (Section 5.2) / ABORT (Sections 5.3.1 and 5.3.2)
   (capitalized "ABORT" in steps)

 curve25519 / Curve25519  (lowercase used much more often)

 curve448 / Curve448  (lowercase used much more often)

 Inputs: / Input:

 Outputs: / Output:

 random oracle encoding / random-oracle encoding
   (We also see "random oracle model"; do these mean "oracle                                      
   encodings or oracle models that are random" or "encodings or                                   
   models of random oracles" (in which case these terms should be
   consistently hyphenated?)

 "RO1" and "RO2" / RO1 and RO2

 Shallue and van de Woestijne map / Shallue-van de Woestijne map

 Shallue and van de Woestijne method / Shallue-van de Woestijne method

 simplified SWU / Simplified SWU (in running text)*
   (We see "simplified SWU" in [BCIMRT10].)

 zero byte / 0-byte (0-bytes, which appears to be the plural
   form of "zero byte")

**Comment by kwantam** [comment]
> abort (Section 5.2) / ABORT (Sections 5.3.1 and 5.3.2) (capitalized "ABORT" in steps)

It would be fine to capitalize in Section 5.2.

> curve25519 / Curve25519 (lowercase used much more often)
>
> curve448 / Curve448 (lowercase used much more often)

Believe it or not, these mean _very_ subtly different things. I just checked and the capitalization looks correct to me, but it would also be fine to ignore the distinction and make it lowercase everywhere (well, perhaps other than in the bibliography since it's someone else's title and their capitalization decision as far as I'm aware).

> Inputs: / Input:
> 
> Outputs: / Output:

I'd vote singular everywhere.

> random oracle encoding / random-oracle encoding (We also see "random oracle model"; do these mean "oracle encodings or oracle models that are random" or "encodings or models of random oracles" (in which case these terms should be consistently hyphenated?)

It should always be hyphenated, as you say :)

> "RO1" and "RO2" / RO1 and RO2

These are correct as written. The quoted strings are literal byte strings, whereas the unquoted ones are function names.

> Shallue and van de Woestijne map / Shallue-van de Woestijne map
> 
> Shallue and van de Woestijne method / Shallue-van de Woestijne method

When referring to the map or method, the version with the dash seems fine. When referring to the authors (e.g., at the start of 6.6.1) I'd leave it "and".

> simplified SWU / Simplified SWU (in running text)* (We see "simplified SWU" in [BCIMRT10].)

My inclination would be to capitalize it consistently. We're using "Simplified SWU" to refer to a specific construction; lower-casing makes "simplified" look like a modifier rather than part of the label.

> zero byte / 0-byte (0-bytes, which appears to be the plural form of "zero byte")

I see "0-bytes" in one spot, and it looks to me like it should say "zero bytes". I could be missing others...

**Comment by kwantam** [comment]
On second thought, maybe it's cleaner just to make "curve25519" and "curve448" lower case everywhere. The distinction is so fine that it almost doesn't matter.

**Comment by lbartholomew-rpc** [comment]
Fixes for Issue #46 are reflected in PR #63.
